// <auto-generated />
using ConcesionarioWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcesionarioWeb.Migrations
{
    [DbContext(typeof(ConcesionarioContext))]
    [Migration("20251005041614_AddVehiculoAndConductor")]
    partial class AddVehiculoAndConductor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConcesionarioWeb.Models.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTipoConductor")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_conductor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoLicencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tipo_licencia");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoConductor");

                    b.ToTable("conductor", "dbo");
                });

            modelBuilder.Entity("ConcesionarioWeb.Models.TipoConductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_conductor", "dbo");
                });

            modelBuilder.Entity("ConcesionarioWeb.Models.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_vehiculo", "dbo");
                });

            modelBuilder.Entity("ConcesionarioWeb.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int")
                        .HasColumnName("año");

                    b.Property<int>("IdTipoVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_vehiculo");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("marca");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matricula");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("modelo");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoVehiculo");

                    b.ToTable("vehiculo", "dbo");
                });

            modelBuilder.Entity("ConcesionarioWeb.Models.Conductor", b =>
                {
                    b.HasOne("ConcesionarioWeb.Models.TipoConductor", "TipoConductor")
                        .WithMany()
                        .HasForeignKey("IdTipoConductor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoConductor");
                });

            modelBuilder.Entity("ConcesionarioWeb.Models.Vehiculo", b =>
                {
                    b.HasOne("ConcesionarioWeb.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("IdTipoVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoVehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
